### ISSUE TITLE
NavigationLink in the resultContent can’t be clicked in.

### ISSUE THREAD

**Issue by NiallLDY** [thislooksfun/SwiftlySearch#12]

**Comment by sherwinzadeh** [comment]
I'm having the same problem. My guess is that it's because UISearchController is presented modally and there is no UINavigationController for NagivationLinks to work. But I'm not sure...

**Comment by NiallLDY** [comment]
> I'm having the same problem. My guess is that it's because UISearchController is presented modally and there is no UINavigationController for NagivationLinks to work. But I'm not sure...

So, any ideas to solve this problem？😂

**Comment by thislooksfun** [comment]
Thanks for bringing this to my attention. Unfortunately, it seems that this is a limitation of how `UISearchController` presents its `searchResultsController` and how that interacts with SwiftUI. As such I can't fix it.

If you want a workaround you could wrap your view in a custom conditional, like so:
```swift
struct ContentView: View {
    @State
    var searchText: String = ""

    var body: some View {
        NavigationView {
            ZStack {
                if searchText.isEmpty {
                    NormalView()
                } else {
                    SearchResultsView(text: searchText)
                }
            }
            .navigationBarSearch($searchText)
        }
    }
}

struct NormalView: View {
    var body: some View {
        Text("Some view")
    }
}

struct SearchResultsView: View {
    var text: String

    var body: some View {
        VStack {
            Text("You searched for \(text)")
            NavigationLink(destination: Text(text)) {
                Text("Let's go!")
            }
        }
    }
}
```
