### ISSUE TITLE
hidden by default? avoid popping in

### ISSUE THREAD

**Issue by esmondmissen** [thislooksfun/SwiftlySearch#4]
Is there a way to have the search bar hidden by default? Currently it just pops in for me and just looks a little jarring. I'm on Xcode 12 beta 3

```swift
List(mylist.filter { searchText == "" ? true : $0.name.localizedStandardContains(searchText) }, id: \.id){ item in
            HStack{
                    Text(item.name)
            }
        }
        .navigationBarTitle("Artists")
        .navigationBarSearch(self.$searchText, placeholder: "Find in Artists")
```

**Comment by thislooksfun** [comment]
There is not currently an option to configure that. it should use the system default behavior. As for the 'popping in' you mentioned, I do not yet have a working beta setup, but once I do I will test to see if I can figure out why it is behaving that way. In the mean time if you could upload a video or gif of this happening that would be useful.

**Comment by thislooksfun** [comment]
I finally got Xcode beta 3 to download, and I can confirm the popping behavior. Not sure why it's happening yet, but I'll look into it.

**Comment by esmondmissen** [comment]
Fixed in iOS 14 beta 4

**Comment by thislooksfun** [comment]
The best kind of bug fix!
