### ISSUE TITLE
Binding text not updated when it changes outside SearchBar

### ISSUE THREAD

**Issue by rubengarciam** [thislooksfun/SwiftlySearch#5]
It seems that the binded search text variable is not updated when the value changes outside the _SearchBar_ view. In other words, the search view is not updated with the new _@State variable_ contents.

Not sure if this is has something to do with the multiple Bindings happening between the _SearchBar_ structure and other coordinators classes, etc?

**Comment by thislooksfun** [comment]
Yeah that's definitely not supposed to happen. I'll look into this when I have time (likely not before next weekend).

**Comment by thislooksfun** [comment]
Fixed in [v1.2.1](https://github.com/thislooksfun/SwiftlySearch/releases/tag/v1.2.1)!

**Comment by rubengarciam** [comment]
awesome, thanks @thislooksfun!
