### ISSUE TITLE
UI content jumps up and down during transition

### ISSUE THREAD

**Issue by eliottrobson** [thislooksfun/SwiftlySearch#7]
I love how smooth this works when using the list as per your example code, however I am trying to use this with different elements. I have setup an example of where the jumping can occur (ScrollView + VStack).

```swift
import SwiftUI
import SwiftlySearch

struct MoviesView: View {
    
    let items: [String] = ["ABC", "DEF", "GHI", "JKL", "MNO", "PQR", "STU", "VWX", "YZ"]
	
    @State
    private var searchText = ""
    
    var body: some View {
        ScrollView {
            VStack {
                ForEach(items.filter { searchText == "" || $0.localizedStandardContains(searchText) }, id: \.self) { item in
                    Text(item)
                }
            }
        }
        .navigationBarTitle("Movies")
        .navigationBarSearch(self.$searchText)
    }

}
```

Here is a recording of the issue which I hope helps to explain
![Sep-18-2020 20-42-54](https://user-images.githubusercontent.com/2973685/93638850-f91abb00-f9ef-11ea-82ef-1f47df8f0a4f.gif)

I am just learning SwiftUI and have no experience with UIKit otherwise I would spend more time trying to fix this myself.
Let me know if you have some ideas and I can do some research and experimentation to help.

EDIT:
I have found this on StackOverflow which demonstrates the exact same issue with UIKit. I am not sure how to implement their solution into this code but I will continue to research.

https://stackoverflow.com/questions/49098249/uitableview-jumps-between-positions-when-activating-and-deactivating-uisearchcon/49156726

Thanks

**Comment by thislooksfun** [comment]
Well that's not supposed to happen, I'll look into it. In the meantime if you need a quick fix you can probably set `hidesNavigationBarDuringPresentation` to `false` which will turn off the animation (change `.navigationBarSearch(self.$searchText)` to `.navigationBarSearch(self.$searchText, hidesNavigationBarDuringPresentation: false)`).

**Comment by eliottrobson** [comment]
The current ~hack~ workaround I am using is to wrap my content in a list, section added to make the spacing a lot nicer.

```swift
init() {
    UITableViewCell.appearance().backgroundColor = .clear
}

// ...

List {
    Section(header: Text("Random Header")) {
        VStack {
            // ...
        }
        .listRowInsets(EdgeInsets())
	.listRowBackground(Color.clear)
    }
    .listRowInsets(EdgeInsets())
}
.listStyle(InsetGroupedListStyle())
```

It looks great, but requires a lot of extra unnecessary elements :)

**Comment by thislooksfun** [comment]
So, turns out that SwiftUI and its overlays (which is how SwiftlySearch works) use a _lot_ of internal (and thus non-app-store-safe) stuff. This doesn't look like a simple fix on my end. I'm going to try to contact Apple to see if their engineers have any ideas, but at this point in time I wouldn't hold my breath for a quick fix.

**Comment by eliottrobson** [comment]
Thanks for getting back to me, it works great for list based content and I'll be sure to use it then / apply workaround or disable the animation when not. Perhaps as SwiftUI grows they will add more support natively.

**Comment by thislooksfun** [comment]
iOS 15 introduced the [`.searchable()`](<https://developer.apple.com/documentation/swiftui/form/searchable(text:placement:)>) api, which is a built-in search bar. As such SwiftlySearch is now deprecated and this issue will not be fixed.
