### ISSUE TITLE
Could you possibly add a way for it to be hidden by default?

### ISSUE THREAD

**Issue by ahmetskilinc** [thislooksfun/SwiftlySearch#8]
I would like to have it behave like it does in the Settings app on iOS.

**Comment by thislooksfun** [comment]
I agree that it would be great if that behavior were configurable, but the last time I looked into it I was unable to make it consistently respect the setting (iirc I was able to get it to _hide_ properly, but I couldn't get it to always _show_). If you or anyone else can implement a `hideOnLoad` (name tbd) parameter, I would be more than happy to merge it.

**Comment by prog666** [comment]
🤔 it's hidden for me and I'm trying to make it visible by default 🤔

**Comment by thislooksfun** [comment]
After doing some totally scientific testing, it seems that whether or not it appears by default depends on whether it's the top level view. Namely, if I have a search bar in the main view of the app it behaves one way but putting it in a sub view (via `NavigationLink`) it behaves the other way, and if I fix one I break the other. If anyone know of why this is or has any ideas on how to fix it, I'm all ears, but until then this sadly seems impossible to fix.

**Comment by thislooksfun** [comment]
iOS 15 introduced the [`.searchable()`](<https://developer.apple.com/documentation/swiftui/form/searchable(text:placement:)>) api, which is a built-in search bar (which is actually hidden by default 🎉). As such SwiftlySearch is now deprecated and this issue will not be fixed.
