### ISSUE TITLE
Updated properties are not propagated correctly into the search bar coordinator

### ISSUE THREAD

**Issue by fwcd** [thislooksfun/SwiftlySearch#9]
Consider the following example:

```swift
struct MyView {
    @State var searchText: String = ""
    @State var placeholder: String = "abc"

    var body: some View {
        NavigationView {
            Button("Click me") { self.placeholder = "123" }
                .navigationBarTitle("Test \(placeholder)")
                .navigationBarSearch($searchText, placeholder)
        }
    }
}
```

One would expect that clicking the button correctly changes _both_ the search placeholder and the title. It, however, only changes the title:

![image](https://user-images.githubusercontent.com/30873659/97900974-c9bfd380-1d3b-11eb-99f3-5084cd4fb58a.png)

Thus the issue seems to be with the search bar. Digging a little deeper, I found that while the [`SearchBar` initializer](https://github.com/thislooksfun/SwiftlySearch/blob/37485cdf86ed9c7af37ca04656df2e653163968d/Sources/SwiftlySearch/SwiftlySearch.swift#L43-L51) is invoked correctly after the state update, no new `Coordinator` is instantiated, thus leaving it with outdated values.

A possible solution might be to update the coordinator in
https://github.com/thislooksfun/SwiftlySearch/blob/37485cdf86ed9c7af37ca04656df2e653163968d/Sources/SwiftlySearch/SwiftlySearch.swift#L57-L64

I am not sure how idiomatic of a solution that would be though.

**Comment by thislooksfun** [comment]
Good catch! This is fixed in [v1.2.2](https://github.com/thislooksfun/SwiftlySearch/releases/tag/v1.2.2)
